name: "Build and Deploy DB Schema"

on:
  push:
    branches: ["prod", "dev"]

permissions: write-all

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ github.repository_owner }}
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release branch if it doesn't exist
        continue-on-error: true
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config pull.rebase true
          resp=`git ls-remote --heads origin release | wc -m | sed 's/ //g'`
          if [ $resp -gt 0 ]; then
            git push origin --delete release
          fi

      - name: Create Release branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release # The branch the action should deploy to.
          folder: . # The folder the action should deploy.

      - name: Checkout Release branch
        uses: actions/checkout@v3
        with:
          ref: release
          path: release

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Replace JS File Contents
        run: |
          cd release/scripts
          sed -e '/JS_CONTENTS/{r schema_builder.js' -e 'd;}' build_graphql_schema.sh > build_graphql_schema.sh.new
          rm -rf build_graphql_schema.sh
          mv build_graphql_schema.sh.new build_graphql_schema.sh
          chmod 777 build_graphql_schema.sh

      - name: Replace PKG File Contents
        run: |
          cd release/scripts
          sed -e '/PKG_JSON_CONTENTS/{r package.json' -e 'd;}' build_graphql_schema.sh > build_graphql_schema.sh.new
          rm -rf build_graphql_schema.sh
          mv build_graphql_schema.sh.new build_graphql_schema.sh
          chmod 777 build_graphql_schema.sh

      - name: Set variables
        id: setvars
        run: |
              if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
                echo "environment=dev" >> $GITHUB_OUTPUT
              fi
    
              if [[ "${{github.base_ref}}" == "prod" || "${{github.ref}}" == "refs/heads/prod" ]]; then
                echo "environment=prod" >> $GITHUB_OUTPUT
              fi

      - name: Commit
        run: |
          cd release
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Release ${{ steps.version.outputs.version }}-${{ steps.setvars.outputs.environment }}"
          git push

      - name: Create release
        uses: "actions/github-script@v6"
        env:
          VERSION: ${{ steps.version.outputs.version }}-${{ steps.setvars.outputs.environment }}
        with:
          github-token: "${{ github.token }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.VERSION,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.VERSION + '-${{ steps.setvars.outputs.environment }}',
                target_commitish: 'release'
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Create workspace
        id: create_workspace
        run: |
          cat > payload.json <<EOF
          {
            "data": {
              "attributes": {
                "name": "${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}",
                "auto-apply": "true"
              },
              "type": "workspaces"
            }
          }
          EOF
          curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @payload.json \
          --output output.txt \
          https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/workspaces
          echo "workspace_id=$(cat output.txt | jq -r '.[].id')" >> $GITHUB_OUTPUT

      - name: Create workspace variables
        run: |
          cat > payload.json <<EOF
          {
            "data": {
              "type":"vars",
              "attributes": {
                "key":"project_name",
                "value":"${{ github.event.repository.name }}",
                "description":"project name",
                "category":"terraform",
                "hcl":false,
                "sensitive":false
              },
              "relationships": {
                "workspace": {
                  "data": {
                    "id":"${{ steps.create_workspace.outputs.workspace_id }}",
                    "type":"workspaces"
                  }
                }
              }
            }
          }
          EOF
          curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @payload.json \
          https://app.terraform.io/api/v2/vars

          cat > payload.json <<EOF
          {
            "data": {
              "type":"vars",
              "attributes": {
                "key":"org_name",
                "value":"${{ github.repository_owner }}",
                "description":"organization name",
                "category":"terraform",
                "hcl":false,
                "sensitive":false
              },
              "relationships": {
                "workspace": {
                  "data": {
                    "id":"${{ steps.create_workspace.outputs.workspace_id }}",
                    "type":"workspaces"
                  }
                }
              }
            }
          }
          EOF
          curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @payload.json \
          https://app.terraform.io/api/v2/vars

          cat > payload.json <<EOF
          {
            "data": {
              "type":"vars",
              "attributes": {
                "key":"environment",
                "value":"${{ steps.setvars.outputs.environment }}",
                "description":"organization name",
                "category":"terraform",
                "hcl":false,
                "sensitive":false
              },
              "relationships": {
                "workspace": {
                  "data": {
                    "id":"${{ steps.create_workspace.outputs.workspace_id }}",
                    "type":"workspaces"
                  }
                }
              }
            }
          }
          EOF
          curl \
          --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @payload.json \
          https://app.terraform.io/api/v2/vars

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
        id: upload
        with:
          workspace: ${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}
          directory: release

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
        id: apply-run
        if: success() || failure()
        with:
          workspace: ${{ github.event.repository.name }}-${{ steps.setvars.outputs.environment }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: false
